### ISSUE TITLE
Create separate areas for user messages and AI's responses

### ISSUE THREAD

**Issue by codesmith-emmy** [codesmith-emmy/gitNarrator#2]
Currently, gitNarrator's interface displays both user's messages and the responses in a single area, making it difficult to distinguish between the two. To improve the overall user experience and clarity, we should create separate areas for user messages and generated responses.

The new interface should have the following components:

1. User Message Area:

- This area should have a clear visual distinction from the response area.
- User messages should be displayed with a distinctive style (e.g., different background color, alignment, or avatar) to differentiate them from the responses.

2. Generated Response Area:

- A separate area where the responses will be displayed.
- Responses should be displayed with a different visual style from the user messages (e.g., different background color, alignment, or avatar).
- Responses should be appended to this area in chronological order, creating a conversational flow.

3. Clear Separation:

- The user message area and response area should be clearly separated, either vertically (one above the other) or horizontally (side by side).
- The separation should be visually distinct and maintain a consistent layout across different screen sizes and devices.

4. Scrolling and History:

- If the conversation becomes lengthy, the response area should have a scrollable view to accommodate the chat history.
- Optionally, we could also consider implementing a feature to save and load chat histories for future reference.

By separating the user messages and responses, we can improve the overall readability and flow of the conversation. Users will be able to easily distinguish their own messages from the responses, enhancing the overall user experience.

**Comment by DodoLintu108** [comment]
I have created a pull request that addresses this issue: [PR #3](https://github.com/codesmith-emmy/gitNarrator/pull/3). Please review the pull request and let me know if there are any adjustments needed.

Thank you!

**Comment by codesmith-emmy** [comment]
Done! Please check pull request for feedback. Thank you
