### ISSUE TITLE
Need for dark mode option 

### ISSUE THREAD

**Issue by Apholabby** [codesmith-emmy/gitNarrator#4]
I would like to request addition of a dark mode feature to reduce eye strain when using app in lowlight environments.

**Comment by MyBaBB** [comment]
## Can you assign this to me?
* I like your app.    
* I can help you with your styles

**Comment by codesmith-emmy** [comment]
Thank you for your interest in contributing @MyBaBB. This [issue](https://github.com/codesmith-emmy/gitNarrator/issues/4) is now assigned to you.

**Comment by MyBaBB** [comment]
Ok, Thanks.. Glad to meet you.

**Comment by MyBaBB** [comment]
I made a nice little dark mode for you,  just let me know if you don't like.  I know its the  Weekend.

**Comment by codesmith-emmy** [comment]
I will review and merge over the weekend. Please give me some time. Thanks

**Comment by MyBaBB** [comment]
Have an enjoyable weekend. Stay cool

**Comment by codesmith-emmy** [comment]
Could you please make the background of User Messages area and AI Response area black in dark mode too?

<img width="1087" alt="Screenshot 2024-07-08 at 21 54 08" src="https://github.com/codesmith-emmy/gitNarrator/assets/154705254/9c9222c2-ddf3-490e-a823-90bfb9723263">

**Comment by MyBaBB** [comment]
Yes,  I can.  It turns out kind of goofy looking,  I will work on it for a
while to see if I can fix it.

**Comment by MyBaBB** [comment]
I got it fixed up pretty good. I madecit mobile responsive and everything.
You can test it and look for canyon bugs I might have missed. Or whatever
you want.
